# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MushroomsCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.TextField(default='untitled', max_length=100, verbose_name='file_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.FileField(unique=True, upload_to='', verbose_name='file_content'),
        ),
    ]
