# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MushroomsCore', '0002_auto_20171023_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.FileField(upload_to='', verbose_name='file_content'),
        ),
    ]
