# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MushroomsCore', '0003_auto_20171023_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='File name',
            field=models.TextField(default='untitled', max_length=100, verbose_name='file_name'),
        ),
    ]
